export const subjectOptions: { value: string; label: string }[] = [
  { value: 'Mathematics', label: 'Mathematics' },
  { value: 'Algebra', label: 'Algebra' },
  { value: 'Geometry', label: 'Geometry' },
  { value: 'Calculus', label: 'Calculus' },
  { value: 'Trigonometry', label: 'Trigonometry' },
  { value: 'Statistics', label: 'Statistics' },
  { value: 'Science', label: 'Science' },
  { value: 'Biology', label: 'Biology' },
  { value: 'Chemistry', label: 'Chemistry' },
  { value: 'Physics', label: 'Physics' },
  { value: 'Environmental Science', label: 'Environmental Science' },
  { value: 'Earth Science', label: 'Earth Science' },
  { value: 'English Language Arts', label: 'English Language Arts' },
  { value: 'Grammar', label: 'Grammar' },
  { value: 'Literature', label: 'Literature' },
  { value: 'Writing', label: 'Writing' },
  { value: 'Reading Comprehension', label: 'Reading Comprehension' },
  { value: 'Social Studies', label: 'Social Studies' },
  {
    value: 'History (World, U.S., Ancient)',
    label: 'History (World, U.S., Ancient)',
  },
  { value: 'Geography', label: 'Geography' },
  { value: 'Economics', label: 'Economics' },
  { value: 'Political Science', label: 'Political Science' },
  { value: 'Foreign Languages', label: 'Foreign Languages' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'French', label: 'French' },
  { value: 'German', label: 'German' },
  { value: 'Chinese (Mandarin)', label: 'Chinese (Mandarin)' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Arabic', label: 'Arabic' },
  { value: 'Russian', label: 'Russian' },
  {
    value: 'Specialized & Advanced Subjects',
    label: 'Specialized & Advanced Subjects',
  },
  { value: 'Advanced Mathematics', label: 'Advanced Mathematics' },
  { value: 'Differential Equations', label: 'Differential Equations' },
  { value: 'Linear Algebra', label: 'Linear Algebra' },
  { value: 'Discrete Math', label: 'Discrete Math' },
  {
    value: 'Computer Science & Technology',
    label: 'Computer Science & Technology',
  },
  {
    value: 'Programming (Python, Java, C++)',
    label: 'Programming (Python, Java, C++)',
  },
  { value: 'Web Development', label: 'Web Development' },
  { value: 'Data Science', label: 'Data Science' },
  { value: 'Cybersecurity', label: 'Cybersecurity' },
  { value: 'AI and Machine Learning', label: 'AI and Machine Learning' },
  { value: 'Business & Economics', label: 'Business & Economics' },
  { value: 'Accounting', label: 'Accounting' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Entrepreneurship', label: 'Entrepreneurship' },
  {
    value: 'Microeconomics/Macroeconomics',
    label: 'Microeconomics/Macroeconomics',
  },
];
export const languageoptions: { value: string; label: string }[] = [
  { value: 'English', label: 'English' },
  { value: 'Mandarin Chinese', label: 'Mandarin Chinese' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'Hindi', label: 'Hindi' },
  { value: 'Arabic', label: 'Arabic' },
  { value: 'French', label: 'French' },
  { value: 'Bengali', label: 'Bengali' },
  { value: 'Russian', label: 'Russian' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Urdu', label: 'Urdu' },
  { value: 'Indonesian', label: 'Indonesian' },
  { value: 'German', label: 'German' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Turkish', label: 'Turkish' },
  { value: 'Korean', label: 'Korean' },
  { value: 'Vietnamese', label: 'Vietnamese' },
  { value: 'Italian', label: 'Italian' },
  { value: 'Thai', label: 'Thai' },
  { value: 'Farsi (Persian)', label: 'Farsi (Persian)' },
  { value: 'Polish', label: 'Polish' },
];
export const subjects = [
  'Mathematics',
  'Algebra',
  'Geometry',
  'Calculus',
  'Trigonometry',
  'Statistics',
  'Science',
  'Biology',
  'Chemistry',
  'Physics',
  'Environmental Science',
  'Earth Science',
  'English Language Arts',
  'Grammar',
  'Literature',
  'Writing',
  'Reading Comprehension',
  'Social Studies',
  'History (World, U.S., Ancient)',
  'Geography',
  'Economics',
  'Political Science',
  'Foreign Languages',
  'Spanish',
  'French',
  'German',
  'Chinese (Mandarin)',
  'Japanese',
  'Arabic',
  'Russian',
  'Specialized & Advanced Subjects',
  'Advanced Mathematics',
  'Differential Equations',
  'Linear Algebra',
  'Discrete Math',
  'Computer Science & Technology',
  'Programming (Python, Java, C++)',
  'Web Development',
  'Data Science',
  'Cybersecurity',
  'AI and Machine Learning',
  'Business & Economics',
  'Accounting',
  'Marketing',
  'Finance',
  'Entrepreneurship',
  'Microeconomics/Macroeconomics',
];
export const degrees = [
  // Undergraduate Degrees
  'Associate Degree (AA, AS)',
  "Bachelor's Degree (BA, BS, BFA, BBA)",
  // Graduate Degrees
  "Master's Degree (MA, MS, MBA, MEd, MFA)",
  'Doctoral Degree (PhD, EdD, DBA)',
  // Professional Degrees
  'Juris Doctor (JD) - Law',
  'Doctor of Medicine (MD)',
  'Doctor of Dental Surgery (DDS)',
  'Doctor of Pharmacy (PharmD)',
  'Master of Architecture (MArch)',
  // Other Degrees
  'Certificate Programs',
  'Diploma Programs',
  'Postgraduate Diploma',
  'Higher National Diploma (HND)',
];
export const countries = [
  'USA',
  // English-Speaking Countries (Americas & Europe)
  'United States',
  'United Kingdom',
  'Ireland',
  'Canada',
  'Malta',
  'Belize',
  // French-Speaking Countries (Americas & Europe)
  'France',
  'Canada (especially Quebec)',
  'Belgium',
  'Switzerland',
  'Luxembourg',
  'Monaco',
  'Haiti',
  // German-Speaking Countries (Europe)
  'Germany',
  'Austria',
  'Liechtenstein',
];
export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
export const levels = [
  'Pre-Kindergarten',
  'Kindergarten-2nd grade',
  '3rd-5th Grade',
  'Middle School',
  'High School',
  'College',
  'Graduate',
  'Adult',
];
export const days: string[] = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];
